
services:
    php:
        build:
            context: ./
            dockerfile: DockerFile
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - container_role=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "8045:8000"
        depends_on:
            - automation-db
        networks:
            - internal
    automation-db:
        image: "mysql"
        ports:
            - "3302:3306"
        volumes:
            - 'db-data-mysql8:/var/lib/mysql'
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        networks:
            - internal

volumes:
    db-data-mysql8:
        driver: local

networks:
    internal:
        driver: bridge
